name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./MooPing.sln

      - name: Build
        run: dotnet build ./MooPing.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./MooPing.sln --configuration Release --no-build
